# Generated by Django 4.1.1 on 2022-09-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='cuerpo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
